name: elsewhere

services:
  elsewhere:
    container_name: elsewhere
    image: ghcr.io/mariepop13/elsewhere:latest
    restart: always
    ports:
      - 6001:6001
    volumes:
      - elsewhere-save:/app/save

volumes:
  elsewhere-save:
